<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cliente extends Model
{
    /* php artisan make:model Cliente */
    use SoftDeletes;
    protected $table = 'clientes';
    protected $fillable = [
            'nombres',
            'apellidos',
            'celular',
            'nit',
            'razon_social',
            'tipo_cliente'];
    protected $dates = ['deleted_at'];

    public function diagnosticos () {
        return $this->hasMany('App\Diagnostico');
    }
    /*Eliminacion en cascada, todos sus registros hijo, mueren tambien*/
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($parent) {
            $parent->diagnosticos()->delete();
        });
    }


}
