<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Oftalmologo extends Model
{
    use SoftDeletes;
    protected $table = 'oftalmologos';
    protected $fillable = [
        'user_id',
        'nit',
        'celular',
    ];
    protected $dates = ['deleted_at'];
    public function user () {
        return $this->belongsTo('App\User');
    }
    public function oftalmologo_opticas () {
        return $this->hasMany('App\OftalmologoOptica');
    }

    public function diagnosticos () {
        return $this->hasMany('App\Diagnostico');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($parent) {
            $parent->oftalmologo_opticas()->delete();
        });
    }


}
